done = 0
ds = global.ds_grid //refer to grid
t = 0 //time begins now
cel = -1 //cell starts empty
written = 0
done_b = 0
max_list = global.max_list //max number of drugs on list
global.count += 1
mull = 0
